name: build

on: pull_request

env:
  DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE: adachikun/qiitatohatena

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: login
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      - name: driver
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: docker buildx create --use --driver docker-container

      - name: build
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker buildx build \
            --tag $IMAGE:latest \
            --platform linux/amd64 \
            --cache-from type=registry,ref=$IMAGE:cache \
            --cache-to type=registry,ref=$IMAGE:cache,mode=max \
            --push \
            .
